<?php

namespace Modules\Seller\Http\Controllers;

use App\Models\User;
use Modules\Core\Http\Controllers\AuthController as BaseAuthController;
use Modules\Seller\Http\Resources\UserResource;

class AuthController extends BaseAuthController
{

  /**
   * overwrite authorized guard
   */
  public $guard = SELLER_GUARD;

  /**
   * overwrite authorized model
   */
  public $model = User::class;
  /**
   * overwrite authorized resource
   */
  public $resource = UserResource::class;

  /**
   * overwrite username to email
   *
   * @return string
   */
  public function username()
  {
    return 'mobile'; // TODO: Change the autogenerated stub
  }
}
